import type { Course } from "@/types/course";

const COURSE_IMAGE_URLS: Record<string, string> = {
  "digital-literacy-essentials":
    "https://images.pexels.com/photos/10638075/pexels-photo-10638075.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "speed-typing-mastery":
    "https://images.pexels.com/photos/5474294/pexels-photo-5474294.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "professional-computer-operator":
    "https://images.pexels.com/photos/3184357/pexels-photo-3184357.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "microsoft-office-professional":
    "https://images.pexels.com/photos/7551442/pexels-photo-7551442.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "advanced-excel-for-professionals":
    "https://images.pexels.com/photos/34639577/pexels-photo-34639577.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "ai-office-administration":
    "https://images.pexels.com/photos/16629368/pexels-photo-16629368.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "software-development-foundation":
    "https://images.pexels.com/photos/3888151/pexels-photo-3888151.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "dsa-competitive-programming":
    "https://images.pexels.com/photos/1102797/pexels-photo-1102797.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "python-for-ai-engineering":
    "https://images.pexels.com/photos/6424590/pexels-photo-6424590.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "modern-frontend-engineering":
    "https://images.pexels.com/photos/29445974/pexels-photo-29445974.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "backend-engineering-with-node-laravel":
    "https://images.pexels.com/photos/1181354/pexels-photo-1181354.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "mern-full-stack-engineering":
    "https://images.pexels.com/photos/36706460/pexels-photo-36706460.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "nextjs-wordpress-development":
    "https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "mobile-app-development":
    "https://images.pexels.com/photos/31450274/pexels-photo-31450274.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "prompt-engineering-masterclass":
    "https://images.pexels.com/photos/15940009/pexels-photo-15940009.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "agentic-ai-automation":
    "https://images.pexels.com/photos/8294608/pexels-photo-8294608.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "llm-rag-systems-development":
    "https://images.pexels.com/photos/17483908/pexels-photo-17483908.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "advanced-ai-software-engineering-diploma":
    "https://images.pexels.com/photos/6804071/pexels-photo-6804071.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "machine-learning-deep-learning":
    "https://images.pexels.com/photos/17483871/pexels-photo-17483871.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "data-analytics-with-power-bi":
    "https://images.pexels.com/photos/12969403/pexels-photo-12969403.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "data-engineering-with-sql-big-data":
    "https://images.pexels.com/photos/5480781/pexels-photo-5480781.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "cloud-devops-engineering":
    "https://images.pexels.com/photos/4597280/pexels-photo-4597280.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "creative-graphic-design-masterclass":
    "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "brand-identity-packaging-design":
    "https://images.pexels.com/photos/3760615/pexels-photo-3760615.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "ui-ux-design-pro":
    "https://images.pexels.com/photos/5594347/pexels-photo-5594347.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "video-editing-motion-graphics":
    "https://images.pexels.com/photos/29505140/pexels-photo-29505140.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "professional-accounting-package":
    "https://images.pexels.com/photos/6694866/pexels-photo-6694866.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "network-engineering-with-ccna":
    "https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "ethical-hacking-cyber-security":
    "https://images.pexels.com/photos/5952645/pexels-photo-5952645.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "cyber-security-professional-ceh-soc-track":
    "https://images.pexels.com/photos/11783119/pexels-photo-11783119.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "digital-marketing-pro":
    "https://images.pexels.com/photos/10628411/pexels-photo-10628411.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "advanced-growth-marketing-automation":
    "https://images.pexels.com/photos/97080/pexels-photo-97080.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "freelancing-online-earning":
    "https://images.pexels.com/photos/12662813/pexels-photo-12662813.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "autocad-design-professional":
    "https://images.pexels.com/photos/7504746/pexels-photo-7504746.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "kids-coding-robotics":
    "https://images.pexels.com/photos/7750751/pexels-photo-7750751.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "career-track-ai-automation-specialist":
    "https://images.pexels.com/photos/32778341/pexels-photo-32778341.jpeg?auto=compress&cs=tinysrgb&w=1400",
  "professional-computer-diploma":
    "https://images.pexels.com/photos/8283954/pexels-photo-8283954.jpeg?auto=compress&cs=tinysrgb&w=1400",
};

const DEFAULT_COURSE_IMAGE =
  "https://images.pexels.com/photos/10638075/pexels-photo-10638075.jpeg?auto=compress&cs=tinysrgb&w=1400";

function getCourseImage(slug: string) {
  return COURSE_IMAGE_URLS[slug] ?? DEFAULT_COURSE_IMAGE;
}

export const courses: Course[] = [
  // ===== Basic Computer (3) =====
  {
    id: "c01",
    slug: "digital-literacy-essentials",
    title: "Digital Literacy Essentials",
    category: "Basic Computer",
    tagline: "Everyday computer, internet and AI skills for total beginners.",
    level: "Beginner",
    duration: "4 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Sunday",
    timing: "Morning / Day / Evening",
    instituteCertificate: "Certificate",
    targetStudents: "SEE Students, +2 Students",
    skillsGained: ["OS navigation", "File management", "Internet & email", "Everyday AI tools", "Digital safety"],
    softwareTools: ["Windows", "Google Workspace", "ChatGPT"],
    portfolioProjects: ["Personal Email Setup", "Basic Document Pack"],
    careerOpportunities: ["Office Assistant", "Data Entry Clerk"],
    image: getCourseImage("digital-literacy-essentials"),
    feeNPR: 3000,
    seoTitle: "Digital Literacy Course for Beginners in Nepal | DarbarTech",
    seoDescription: "Learn everyday computer, internet, and AI skills in 4 weeks — built for absolute beginners.",
    cta: "Start Your First Computer Course",
    shortDescription: "Build essential computer, internet, and everyday AI skills for total beginners in just one month.",
  },
  {
    id: "c02",
    slug: "speed-typing-mastery",
    title: "Speed Typing Mastery",
    category: "Basic Computer",
    tagline: "Type fast, type accurate, get exam and job ready.",
    level: "Beginner",
    duration: "4 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Sunday",
    timing: "Morning / Day / Evening",
    instituteCertificate: "Certificate",
    targetStudents: "SEE Students, +2 Students, Job Seekers",
    shortDescription: "Master fast, accurate English and Nepali typing with certified speed tests for office and exam readiness.",
    skillsGained: ["Touch-typing technique", "English & Nepali typing", "Speed & accuracy", "Keyboard shortcuts"],
    softwareTools: ["Typing Master", "RapidTyping"],
    portfolioProjects: ["Certified Speed Test Report"],
    careerOpportunities: ["Data Entry Operator", "Office Assistant"],
    image: getCourseImage("speed-typing-mastery"),
    feeNPR: 3000,
    seoTitle: "Speed Typing Course in Kathmandu (English & Nepali) | DarbarTech",
    seoDescription: "Type faster and more accurately with certified speed tests — job and exam ready in 4 weeks.",
    cta: "Book a Typing Assessment",
  },
  {
    id: "c03",
    slug: "professional-computer-operator",
    title: "Professional Computer Operator",
    category: "Basic Computer",
    tagline: "A complete beginner-to-job-ready operator package.",
    level: "Beginner",
    duration: "12 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Morning / Day",
    instituteCertificate: "Diploma",
    industryCertification: "Microsoft",
    internship: "Optional Internship",
    targetStudents: "SEE Students, +2 Students, Job Seekers",
    skillsGained: ["Typing", "MS Office", "Internet & email", "Data entry", "Basic troubleshooting", "Office etiquette"],
    softwareTools: ["MS Word", "Excel", "PowerPoint", "Google Workspace"],
    portfolioProjects: ["Office Records System", "Data Entry Portfolio"],
    careerOpportunities: ["Computer Operator", "Office Assistant", "Data Entry Officer"],
    image: getCourseImage("professional-computer-operator"),
    featured: true,
    feeNPR: 9000,
    feeNote: "Installments available",
    seats: "Limited seats",
    seoTitle: "Professional Computer Operator Course in Kathmandu | DarbarTech",
    seoDescription: "Become a job-ready computer operator in 12 weeks. Typing, MS Office, data entry, and troubleshooting — hands-on training with a Microsoft-aligned diploma.",
    overview: "A complete beginner-to-job-ready package built for SEE/+2 graduates and job seekers who want one course that covers everything an office expects: fast typing, Office software fluency, internet and email literacy, and basic troubleshooting.",
    learningObjectives: ["Type accurately and quickly in English and Nepali", "Operate MS Word, Excel, and PowerPoint confidently", "Manage email, internet research, and basic file systems", "Handle everyday data-entry and office-etiquette scenarios"],
    prerequisites: "None — built for absolute beginners",
    cta: "Get Your Batch Timing & Enrollment Details",
    shortDescription: "A complete beginner-to-job-ready package combining typing, Office software, and internet skills for operator roles.",
  },

  // ===== Office & Productivity (3) =====
  {
    id: "c04",
    slug: "microsoft-office-professional",
    title: "Microsoft Office Professional",
    category: "Office & Productivity",
    tagline: "Master the Office suite every workplace runs on.",
    level: "Beginner",
    duration: "8 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Sunday",
    timing: "Morning / Day / Evening",
    instituteCertificate: "Certificate",
    industryCertification: "Microsoft",
    targetStudents: "+2 Students, Job Seekers, Working Professionals",
    shortDescription: "Gain hands-on mastery of Word, Excel, PowerPoint and AI-assisted Office tools used in every workplace.",
    skillsGained: ["Word", "Excel", "PowerPoint", "Outlook", "Copilot AI basics", "Document formatting"],
    softwareTools: ["MS Word", "Excel", "PowerPoint", "Outlook", "Copilot"],
    portfolioProjects: ["Business Report", "Sales Presentation", "Budget Sheet"],
    careerOpportunities: ["Office Assistant", "Admin Executive", "Data Entry Officer"],
    image: getCourseImage("microsoft-office-professional"),
    feeNPR: 7000,
    feeNote: "Installments available",
    seoTitle: "MS Office Course in Nepal (Word, Excel, PowerPoint) | DarbarTech",
    seoDescription: "Master the Office suite every workplace uses, plus Copilot AI basics, in 8 weeks.",
    cta: "Enroll in the Next Office Batch",
  },
  {
    id: "c05",
    slug: "advanced-excel-for-professionals",
    title: "Advanced Excel for Professionals",
    category: "Office & Productivity",
    tagline: "Turn spreadsheets into powerful business dashboards.",
    level: "Intermediate",
    duration: "4 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Microsoft",
    targetStudents: "Working Professionals, Business Owners",
    shortDescription: "Build powerful Excel dashboards and automate reports using pivot tables, Power Query, and advanced formulas.",
    skillsGained: ["Pivot tables", "Power Query", "Dashboards", "Advanced formulas", "Macro basics"],
    softwareTools: ["MS Excel", "Power Query", "Power BI"],
    portfolioProjects: ["Sales Dashboard", "Automated Report Template"],
    careerOpportunities: ["Data Analyst", "Finance Executive", "Business Analyst"],
    image: getCourseImage("advanced-excel-for-professionals"),
    feeNPR: 6500,
  },
  {
    id: "c06",
    slug: "ai-office-administration",
    title: "AI Office Administration",
    category: "Office & Productivity",
    tagline: "Run any office with AI-assisted efficiency.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Day",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Microsoft",
    internship: "Optional Internship",
    targetStudents: "Job Seekers, Working Professionals",
    shortDescription: "Learn modern office administration enhanced with AI drafting and scheduling tools to run any workplace.",
    skillsGained: ["Correspondence", "Scheduling", "AI-assisted drafting", "Record-keeping", "Workflow tools"],
    softwareTools: ["MS Office", "Outlook", "ChatGPT", "Notion"],
    portfolioProjects: ["Office Workflow System", "AI Email Templates"],
    careerOpportunities: ["Office Administrator", "Executive Assistant", "HR Coordinator"],
    image: getCourseImage("ai-office-administration"),
    feeNPR: 9000,
    feeNote: "Installments available",
    seats: "Limited seats",
  },

  // ===== Programming (3) =====
  {
    id: "c07",
    slug: "software-development-foundation",
    title: "Software Development Foundation",
    category: "Programming",
    tagline: "Build the coding logic every developer starts with.",
    level: "Beginner",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Certificate",
    targetStudents: "+2 Students, Bachelor Students",
    shortDescription: "Build a strong programming foundation in C, Python and Java through logic-based, hands-on practice.",
    skillsGained: ["C/C++ basics", "Python fundamentals", "Logic building", "Problem-solving", "Java basics"],
    softwareTools: ["VS Code", "Git", "GitHub", "Python", "C++"],
    portfolioProjects: ["Console Calculator", "Student Management System"],
    careerOpportunities: ["Junior Programmer", "Trainee Developer"],
    image: getCourseImage("software-development-foundation"),
    feeNPR: 13000,
    seoTitle: "Beginner Programming Course (C, Python, Java) in Nepal | DarbarTech",
    seoDescription: "Build real coding logic in C, Python, and Java — the foundation every developer starts with.",
    cta: "Start Coding From Scratch",
  },
  {
    id: "c08",
    slug: "dsa-competitive-programming",
    title: "DSA & Competitive Programming",
    category: "Programming",
    tagline: "Sharpen problem-solving for interviews and contests.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Certificate",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Master data structures and algorithms to crack coding interviews and competitive programming contests.",
    skillsGained: ["Data structures", "Algorithms", "Time complexity", "Interview problem patterns", "Contest practice"],
    softwareTools: ["VS Code", "Git", "LeetCode", "Codeforces"],
    portfolioProjects: ["Algorithm Visualizer", "Coding Contest Portfolio"],
    careerOpportunities: ["Software Engineer", "SDE Intern", "Backend Developer"],
    image: getCourseImage("dsa-competitive-programming"),
    feeNPR: 14000,
    seats: "Limited seats",
    seoTitle: "Data Structures & Algorithms Course in Kathmandu | DarbarTech",
    seoDescription: "Sharpen your problem-solving for coding interviews and contests in 8 weeks.",
    cta: "Prepare for Coding Interviews",
  },
  {
    id: "c09",
    slug: "python-for-ai-engineering",
    title: "Python for AI Engineering",
    category: "Programming",
    tagline: "Build intelligent software using modern AI tools.",
    level: "Intermediate",
    duration: "12 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn Python programming combined with practical AI integration to build smart, automated applications.",
    skillsGained: ["Python", "OOP", "APIs", "AI libraries", "Automation scripting"],
    softwareTools: ["Python", "VS Code", "OpenAI API", "Git"],
    portfolioProjects: ["AI Chatbot", "Resume Generator", "AI Content Tool"],
    careerOpportunities: ["AI Developer", "Python Developer", "Automation Engineer"],
    image: getCourseImage("python-for-ai-engineering"),
    feeNPR: 18000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
    seoTitle: "Python for AI Course in Nepal | DarbarTech",
    seoDescription: "Learn Python and practical AI integration to build smart, automated applications.",
    cta: "Build Your First AI App",
  },

  // ===== Web Development (5) =====
  {
    id: "c10",
    slug: "modern-frontend-engineering",
    title: "Modern Frontend Engineering",
    category: "Web Development",
    tagline: "Design beautiful, responsive websites for real businesses.",
    level: "Intermediate",
    duration: "16 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Meta",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    skillsGained: ["HTML/CSS/JS", "React & Next.js", "Tailwind CSS", "AI pair-programming", "Responsive design"],
    softwareTools: ["VS Code", "React", "Next.js", "Tailwind CSS", "GitHub Copilot"],
    portfolioProjects: ["Restaurant Website", "Ecommerce Frontend", "School Website"],
    careerOpportunities: ["Frontend Developer", "React Developer", "UI Engineer"],
    image: getCourseImage("modern-frontend-engineering"),
    featured: true,
    feeNPR: 28000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats, cohort-based intake",
    seoTitle: "Frontend Web Development Course (React & Next.js) in Nepal | DarbarTech",
    seoDescription: "Learn React, Next.js, and Tailwind CSS hands-on in 16 weeks. Build a real portfolio, get Meta-aligned certification, and start your frontend developer career.",
    overview: "A 16-week, project-driven course for anyone who wants to build modern, responsive websites and interfaces — not just follow tutorials. You'll use the same tools and AI-assisted workflows professional frontend teams use today.",
    learningObjectives: ["Build responsive UIs with HTML/CSS/JS", "Develop with React and Next.js", "Style efficiently with Tailwind CSS", "Use AI pair-programming tools productively", "Ship three portfolio-ready websites"],
    prerequisites: "Basic computer literacy; no prior coding required",
    cta: "Reserve Your Seat in the Next Cohort",
    shortDescription: "Build modern, responsive websites and interfaces using React, Next.js, and AI-assisted coding tools.",
  },
  {
    id: "c11",
    slug: "backend-engineering-with-node-laravel",
    title: "Backend Engineering with Node & Laravel",
    category: "Web Development",
    tagline: "Power real applications from the server side.",
    level: "Intermediate",
    duration: "16 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn to design and build secure, scalable backend systems and APIs using Node.js and Laravel.",
    skillsGained: ["Node.js & Express", "Laravel/PHP", "REST APIs", "Databases", "Auth & JWT"],
    softwareTools: ["Node.js", "Express", "Laravel", "MySQL", "Postman"],
    portfolioProjects: ["Booking API", "Inventory System", "Auth Service"],
    careerOpportunities: ["Backend Developer", "API Engineer", "PHP/Node Developer"],
    image: getCourseImage("backend-engineering-with-node-laravel"),
    feeNPR: 28000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
    seoTitle: "Backend Development Course (Node.js & Laravel) Nepal | DarbarTech",
    seoDescription: "Design secure, scalable backend systems and APIs in 16 weeks of hands-on training.",
    cta: "Build Real Backend Systems",
  },
  {
    id: "c12",
    slug: "mern-full-stack-engineering",
    title: "MERN Full Stack Engineering",
    category: "Web Development",
    tagline: "Become a complete web developer from database to launch.",
    level: "Advanced",
    duration: "24 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Diploma",
    industryCertification: "Meta",
    internship: "Internship Available",
    targetStudents: "Bachelor Students, Job Seekers",
    skillsGained: ["Node.js & Express", "MongoDB/MySQL", "REST APIs", "Auth & JWT", "Deployment & CI/CD"],
    softwareTools: ["React", "Node.js", "MongoDB", "Express", "Docker", "GitHub"],
    portfolioProjects: ["Ecommerce Platform", "Job Portal", "Social Media App"],
    careerOpportunities: ["Full Stack Developer", "MERN Developer", "Software Engineer"],
    image: getCourseImage("mern-full-stack-engineering"),
    featured: true,
    feeNPR: 45000,
    feeNote: "4-part installment plan available",
    seats: "Limited seats, cohort-based intake",
    seoTitle: "MERN Full Stack Development Course in Kathmandu | DarbarTech",
    seoDescription: "Become a complete full-stack developer in 24 weeks. MongoDB, Express, React, Node — build and deploy real production apps with internship support.",
    overview: "DarbarTech's most comprehensive web development track. Over 24 weeks, you go from database design to a deployed, production-style application — the kind of project that anchors a strong developer portfolio.",
    learningObjectives: ["Design REST APIs with Node.js/Express", "Work with MongoDB and MySQL", "Implement authentication and JWT", "Deploy applications with Docker and CI/CD basics", "Ship an ecommerce platform, job portal, or social app"],
    prerequisites: "Basic programming logic (covered in Software Development Foundation, if needed)",
    cta: "Check Seats for the Next Cohort",
    shortDescription: "Become a complete web developer, building and deploying full production apps from database to launch.",
  },
  {
    id: "c13",
    slug: "nextjs-wordpress-development",
    title: "Next.js & WordPress Development",
    category: "Web Development",
    tagline: "Ship fast websites for startups and small businesses.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Certificate",
    targetStudents: "Bachelor Students, Freelancers, Job Seekers",
    shortDescription: "Build fast marketing sites and client websites using Next.js and WordPress, ready to deploy and sell.",
    skillsGained: ["Next.js SSR/SSG", "WordPress theming", "Elementor", "SEO basics", "Hosting & deployment"],
    softwareTools: ["Next.js", "WordPress", "Elementor", "Vercel", "cPanel"],
    portfolioProjects: ["Business Landing Page", "WordPress Business Site"],
    careerOpportunities: ["Web Developer", "WordPress Developer", "Freelancer"],
    image: getCourseImage("nextjs-wordpress-development"),
    feeNPR: 14000,
    seoTitle: "Next.js & WordPress Course in Kathmandu | DarbarTech",
    seoDescription: "Build fast marketing sites and client websites, ready to deploy and sell, in 8 weeks.",
    cta: "Start Building Client Websites",
  },
  {
    id: "c14",
    slug: "mobile-app-development",
    title: "Mobile App Development",
    category: "Web Development",
    tagline: "Launch real Android and iOS apps with one codebase.",
    level: "Intermediate",
    duration: "16 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers, Freelancers",
    shortDescription: "Design and launch real Android/iOS apps using Flutter and React Native with live API integration.",
    skillsGained: ["Flutter", "React Native", "Firebase", "API integration", "App deployment"],
    softwareTools: ["Flutter", "React Native", "Firebase", "Android Studio"],
    portfolioProjects: ["Food Delivery App", "Chat App", "Expense Tracker App"],
    careerOpportunities: ["Mobile App Developer", "Flutter Developer", "App Freelancer"],
    image: getCourseImage("mobile-app-development"),
    feeNPR: 30000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
    seoTitle: "Flutter & React Native Course in Nepal | DarbarTech",
    seoDescription: "Launch real Android and iOS apps with one codebase using Flutter and React Native.",
    cta: "Launch Your First Mobile App",
  },

  // ===== AI & Automation (4) =====
  {
    id: "c15",
    slug: "prompt-engineering-masterclass",
    title: "Prompt Engineering Masterclass",
    category: "AI & Automation",
    tagline: "Turn AI chat tools into a career superpower.",
    level: "Beginner",
    duration: "3 Weeks",
    learningMode: "Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Certificate",
    targetStudents: "Working Professionals, Business Owners, Freelancers",
    skillsGained: ["Prompt engineering", "ChatGPT/Claude/Gemini workflows", "AI content generation", "AI image & video tools"],
    softwareTools: ["ChatGPT", "Claude", "Gemini", "Cursor AI"],
    portfolioProjects: ["AI Content Playbook", "Automated Prompt Library"],
    careerOpportunities: ["AI Consultant", "Content Strategist", "Freelancer"],
    image: getCourseImage("prompt-engineering-masterclass"),
    featured: true,
    feeNPR: 4500,
    seoTitle: "Prompt Engineering Course in Nepal (ChatGPT, Claude, Gemini) | DarbarTech",
    seoDescription: "A 3-week hands-on course to master ChatGPT, Claude, and Gemini for work — smarter prompting, AI content, and automation for professionals and freelancers.",
    overview: "The fastest-growing skill gap in Nepal's job market right now isn't coding — it's knowing how to actually get useful output from AI tools. This short, practical course turns casual ChatGPT users into people who save hours every week.",
    learningObjectives: ["Write structured, reusable prompts", "Compare ChatGPT, Claude, and Gemini for different tasks", "Use AI for content, image, and basic video generation", "Build a personal prompt library for repeat use"],
    prerequisites: "Basic computer and internet use",
    cta: "Join the Next 3-Week Batch",
    shortDescription: "Learn to use ChatGPT, Claude and Gemini effectively to save hours of work through smart prompting.",
  },
  {
    id: "c16",
    slug: "agentic-ai-automation",
    title: "Agentic AI & Automation",
    category: "AI & Automation",
    tagline: "Build real AI agents that do the work for you.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    internship: "Optional Internship",
    targetStudents: "Job Seekers, Working Professionals",
    shortDescription: "Build real AI-powered agents and automation pipelines using modern LLM APIs and no-code tools.",
    skillsGained: ["LLM APIs", "RAG & vector databases", "Agent workflows", "No-code automation", "AI ethics basics"],
    softwareTools: ["OpenAI API", "LangChain", "Zapier/n8n", "Pinecone"],
    portfolioProjects: ["AI Support Agent", "Automated Workflow Bot"],
    careerOpportunities: ["AI Automation Engineer", "Workflow Consultant"],
    image: getCourseImage("agentic-ai-automation"),
    feeNPR: 16000,
    feeNote: "Installments available",
    seoTitle: "AI Automation Course in Nepal (LLM Agents) | DarbarTech",
    seoDescription: "Build real AI-powered agents and automation pipelines with modern LLM APIs.",
    cta: "Build Your First AI Agent",
  },
  {
    id: "c17",
    slug: "llm-rag-systems-development",
    title: "LLM & RAG Systems Development",
    category: "AI & Automation",
    tagline: "Build the tech behind ChatGPT-style products.",
    level: "Advanced",
    duration: "10 Weeks",
    learningMode: "Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn to design and deploy retrieval-augmented and agentic LLM systems using modern frameworks like MCP.",
    skillsGained: ["LLM fine-tuning basics", "RAG pipelines", "Vector databases", "MCP development", "Model evaluation"],
    softwareTools: ["Python", "LangChain", "Pinecone/Chroma", "Claude API", "MCP"],
    portfolioProjects: ["RAG Knowledge Assistant", "MCP-Connected Tool", "LLM-Powered App"],
    careerOpportunities: ["LLM Developer", "AI Engineer", "Applied AI Researcher"],
    image: getCourseImage("llm-rag-systems-development"),
    feeNPR: 22000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
    seoTitle: "LLM & RAG Development Course in Kathmandu | DarbarTech",
    seoDescription: "Design and deploy retrieval-augmented and agentic LLM systems using modern frameworks.",
    cta: "Build Production-Grade AI Systems",
  },
  {
    id: "c18",
    slug: "advanced-ai-software-engineering-diploma",
    title: "Advanced AI Software Engineering Diploma",
    category: "AI & Automation",
    tagline: "A flagship one-year diploma for AI-native developers.",
    level: "Advanced",
    duration: "48 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Advanced Diploma",
    industryCertification: "Microsoft, Google",
    internship: "Internship Available",
    targetStudents: "Bachelor Students, Job Seekers",
    skillsGained: ["Full stack development", "LLM integration", "Cloud deployment", "DevOps basics", "Capstone project"],
    softwareTools: ["React", "Node.js", "Python", "AWS", "Docker", "GitHub"],
    portfolioProjects: ["Capstone AI Product", "Full Stack SaaS App"],
    careerOpportunities: ["AI Software Engineer", "Full Stack Developer", "Product Engineer"],
    image: getCourseImage("advanced-ai-software-engineering-diploma"),
    featured: true,
    feeNPR: 75000,
    feeNote: "6-part installment plan available",
    seats: "Limited seats, cohort-based intake",
    seoTitle: "AI Software Engineering Diploma (1-Year Program) Nepal | DarbarTech",
    seoDescription: "DarbarTech's flagship 48-week diploma: full-stack development, LLM integration, and cloud deployment. Build a capstone AI product with internship support.",
    overview: "A one-year, career-defining diploma for students who want to graduate with more than a certificate — a working, deployed AI-integrated software product they built themselves, plus the full-stack and cloud fundamentals to keep building after graduation.",
    learningObjectives: ["Build full-stack applications end-to-end", "Integrate LLMs into real products", "Deploy on cloud infrastructure (AWS)", "Apply DevOps fundamentals", "Complete a capstone AI product from scratch"],
    prerequisites: "Comfort with computers; prior programming exposure helpful but not mandatory — foundational modules are included",
    cta: "Apply for the Next Intake",
    shortDescription: "A flagship one-year diploma combining full stack development with AI integration and cloud deployment skills.",
  },

  // ===== Data Science (3) =====
  {
    id: "c19",
    slug: "machine-learning-deep-learning",
    title: "Machine Learning & Deep Learning",
    category: "Data Science",
    tagline: "Train the models powering modern AI products.",
    level: "Advanced",
    duration: "16 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn to build and evaluate machine learning and deep learning models using Python, PyTorch and TensorFlow.",
    skillsGained: ["Python, NumPy, Pandas", "ML algorithms", "Deep learning", "Model evaluation"],
    softwareTools: ["Python", "PyTorch", "TensorFlow", "Jupyter"],
    portfolioProjects: ["Price Prediction Model", "Image Classifier", "Recommendation Engine"],
    careerOpportunities: ["Machine Learning Engineer", "Data Scientist", "AI Researcher"],
    image: getCourseImage("machine-learning-deep-learning"),
    feeNPR: 32000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
    seoTitle: "Machine Learning Course in Nepal (PyTorch & TensorFlow) | DarbarTech",
    seoDescription: "Build and evaluate ML and deep learning models using Python, PyTorch, and TensorFlow.",
    cta: "Start Your ML Portfolio",
  },
  {
    id: "c20",
    slug: "data-analytics-with-power-bi",
    title: "Data Analytics with Power BI",
    category: "Data Science",
    tagline: "Turn raw business data into decisions.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Microsoft",
    internship: "Optional Internship",
    targetStudents: "Working Professionals, Job Seekers",
    shortDescription: "Turn raw business data into actionable dashboards and insights using SQL and Power BI.",
    skillsGained: ["SQL", "Power BI", "Data cleaning", "Data visualization", "Storytelling with data"],
    softwareTools: ["SQL", "Power BI", "Excel", "Python"],
    portfolioProjects: ["Sales Analytics Dashboard", "KPI Report"],
    careerOpportunities: ["Data Analyst", "Business Intelligence Analyst"],
    image: getCourseImage("data-analytics-with-power-bi"),
    feeNPR: 14000,
    seats: "Limited seats",
    seoTitle: "Power BI & Data Analytics Course in Kathmandu | DarbarTech",
    seoDescription: "Turn raw business data into dashboards and insights using SQL and Power BI.",
    cta: "Turn Data Into Decisions",
  },
  {
    id: "c21",
    slug: "data-engineering-with-sql-big-data",
    title: "Data Engineering with SQL & Big Data",
    category: "Data Science",
    tagline: "Build the data pipelines every AI system depends on.",
    level: "Advanced",
    duration: "12 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn to design and manage the ETL pipelines and big data infrastructure behind modern analytics and AI.",
    skillsGained: ["SQL Server", "ETL pipelines", "Apache Spark", "Big data fundamentals", "Cloud data warehousing"],
    softwareTools: ["SQL Server", "Apache Spark", "Airflow", "AWS/Azure"],
    portfolioProjects: ["ETL Pipeline", "Data Warehouse Model", "Streaming Data Dashboard"],
    careerOpportunities: ["Data Engineer", "ETL Developer", "Cloud Data Analyst"],
    image: getCourseImage("data-engineering-with-sql-big-data"),
    feeNPR: 25000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
    seoTitle: "Data Engineering Course in Nepal (SQL & Spark) | DarbarTech",
    seoDescription: "Design ETL pipelines and big data infrastructure behind modern analytics and AI.",
    cta: "Build Your First Data Pipeline",
  },

  // ===== Cloud & DevOps (1) =====
  {
    id: "c22",
    slug: "cloud-devops-engineering",
    title: "Cloud & DevOps Engineering",
    category: "Cloud & DevOps",
    tagline: "Deploy, scale and automate like a modern tech company.",
    level: "Advanced",
    duration: "12 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "AWS, Microsoft",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers, Working Professionals",
    shortDescription: "Learn to deploy, containerize and automate applications on AWS and Azure using industry DevOps practices.",
    skillsGained: ["AWS & Azure fundamentals", "Docker", "Kubernetes", "CI/CD pipelines", "Linux administration"],
    softwareTools: ["AWS", "Azure", "Docker", "Kubernetes", "Jenkins", "Linux"],
    portfolioProjects: ["Containerized App Deployment", "CI/CD Pipeline", "Cloud Infrastructure Setup"],
    careerOpportunities: ["DevOps Engineer", "Cloud Engineer", "Site Reliability Engineer"],
    image: getCourseImage("cloud-devops-engineering"),
    feeNPR: 28000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
    seoTitle: "AWS & DevOps Course in Kathmandu | DarbarTech",
    seoDescription: "Deploy, containerize, and automate applications on AWS and Azure like a modern tech team.",
    cta: "Start Deploying Like a Pro",
  },

  // ===== Graphic Design (3) =====
  {
    id: "c23",
    slug: "creative-graphic-design-masterclass",
    title: "Creative Graphic Design Masterclass",
    category: "Graphic Design",
    tagline: "Turn creativity into a professional career.",
    level: "Intermediate",
    duration: "12 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Adobe",
    internship: "Optional Internship",
    targetStudents: "+2 Students, Freelancers, Job Seekers",
    skillsGained: ["Photoshop", "Illustrator", "Canva AI", "Branding design", "Print design"],
    softwareTools: ["Photoshop", "Illustrator", "Canva", "Figma"],
    portfolioProjects: ["Logo Design", "Business Card", "Brochure", "Social Media Campaign"],
    careerOpportunities: ["Graphic Designer", "Social Media Designer", "Branding Designer", "Freelancer"],
    image: getCourseImage("creative-graphic-design-masterclass"),
    featured: true,
    feeNPR: 16000,
    feeNote: "Installments available",
    seats: "Limited seats",
    seoTitle: "Graphic Design Course in Kathmandu (Photoshop, Illustrator, AI Tools) | DarbarTech",
    seoDescription: "Learn Photoshop, Illustrator, and AI design tools in 12 weeks. Build a real portfolio — logos, branding, social media — with Adobe-aligned certification.",
    overview: "For anyone whose creativity has outgrown Canva templates, this course builds real design fluency — the software skills, the branding logic, and the portfolio pieces employers and clients actually ask to see.",
    learningObjectives: ["Design in Photoshop and Illustrator confidently", "Use Canva AI and Figma for faster workflows", "Apply branding and print-design principles", "Produce a client-ready design portfolio"],
    prerequisites: "None — beginner-friendly, some creative interest helpful",
    cta: "See the Full Design Curriculum",
    shortDescription: "Master Photoshop, Illustrator and AI design tools to create logos, brochures and social media graphics.",
  },
  {
    id: "c24",
    slug: "brand-identity-packaging-design",
    title: "Brand Identity & Packaging Design",
    category: "Graphic Design",
    tagline: "Design the visual identity brands are built on.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Adobe",
    targetStudents: "Freelancers, Job Seekers",
    shortDescription: "Learn to build complete brand identities and packaging designs used by real product companies.",
    skillsGained: ["Brand identity systems", "Packaging design", "Print production", "Motion graphics basics", "UI animation basics"],
    softwareTools: ["Illustrator", "Photoshop", "InDesign", "After Effects"],
    portfolioProjects: ["Brand Identity Kit", "Product Packaging", "Motion Logo"],
    careerOpportunities: ["Brand Designer", "Packaging Designer", "Motion Graphics Artist"],
    image: getCourseImage("brand-identity-packaging-design"),
    feeNPR: 15000,
  },
  {
    id: "c25",
    slug: "ui-ux-design-pro",
    title: "UI/UX Design Pro",
    category: "Graphic Design",
    tagline: "Design user-friendly apps and websites people love.",
    level: "Intermediate",
    duration: "12 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers, Freelancers",
    shortDescription: "Design user-friendly apps and websites using Figma, from wireframes to fully tested prototypes.",
    skillsGained: ["Figma", "Wireframing", "Prototyping", "Design systems", "Usability testing"],
    softwareTools: ["Figma", "Adobe XD", "Miro"],
    portfolioProjects: ["Mobile App Prototype", "Design System", "Usability Test Report"],
    careerOpportunities: ["UI/UX Designer", "Product Designer", "Freelancer"],
    image: getCourseImage("ui-ux-design-pro"),
    feeNPR: 18000,
    feeNote: "Installments available",
    seats: "Limited seats",
    seoTitle: "UI/UX Design Course in Kathmandu (Figma) | DarbarTech",
    seoDescription: "Design user-friendly apps and websites in Figma, from wireframes to tested prototypes.",
    cta: "Start Your UX Portfolio",
  },

  // ===== Video Production (1) =====
  {
    id: "c26",
    slug: "video-editing-motion-graphics",
    title: "Video Editing & Motion Graphics",
    category: "Video Production",
    tagline: "Edit content that stops the scroll.",
    level: "Intermediate",
    duration: "10 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Adobe",
    internship: "Optional Internship",
    targetStudents: "Freelancers, Job Seekers, Business Owners",
    shortDescription: "Edit professional videos and motion graphics for YouTube, Reels and business using industry-standard tools.",
    skillsGained: ["Premiere Pro", "After Effects", "DaVinci Resolve", "AI video tools", "Short-form editing"],
    softwareTools: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
    portfolioProjects: ["YouTube Video Edit", "Reels Campaign", "Motion Graphics Intro"],
    careerOpportunities: ["Video Editor", "Motion Graphics Artist", "Content Creator"],
    image: getCourseImage("video-editing-motion-graphics"),
    feeNPR: 15000,
    seats: "Limited seats",
    seoTitle: "Video Editing Course in Nepal (Premiere Pro, After Effects) | DarbarTech",
    seoDescription: "Edit professional videos and motion graphics for YouTube, Reels, and business use.",
    cta: "Start Editing Like a Pro",
  },

  // ===== Business & Accounting (1) =====
  {
    id: "c27",
    slug: "professional-accounting-package",
    title: "Professional Accounting Package",
    category: "Business & Accounting",
    tagline: "Manage books and GST-ready accounts with confidence.",
    level: "Beginner",
    duration: "6 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Morning / Day",
    instituteCertificate: "Certificate",
    targetStudents: "Job Seekers, Business Owners",
    shortDescription: "Learn Tally Prime and Excel to manage bookkeeping, billing and GST-ready accounts for any business.",
    skillsGained: ["Tally Prime", "GST/VAT entries", "Inventory management", "Excel for accounting"],
    softwareTools: ["Tally Prime", "Excel"],
    portfolioProjects: ["Company Books Setup", "GST Filing Practice"],
    careerOpportunities: ["Accountant", "Billing Executive", "Inventory Officer"],
    image: getCourseImage("professional-accounting-package"),
    feeNPR: 8000,
    seoTitle: "Tally & Accounting Course in Kathmandu | DarbarTech",
    seoDescription: "Manage bookkeeping, billing, and GST-ready accounts with Tally Prime and Excel.",
    cta: "Get Job-Ready in Accounting",
  },

  // ===== Networking (1) =====
  {
    id: "c28",
    slug: "network-engineering-with-ccna",
    title: "Network Engineering with CCNA",
    category: "Networking",
    tagline: "Build the networks powering Nepal's ISPs and IT firms.",
    level: "Intermediate",
    duration: "12 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Cisco",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Build job-ready networking skills with CCNA and MikroTik training used across Nepal's ISPs and IT firms.",
    skillsGained: ["Networking fundamentals", "CCNA", "MikroTik routing", "Server basics"],
    softwareTools: ["Cisco Packet Tracer", "MikroTik", "VMware"],
    portfolioProjects: ["Office Network Design", "Router Configuration Lab"],
    careerOpportunities: ["Network Engineer", "IT Support Engineer", "ISP Technician"],
    image: getCourseImage("network-engineering-with-ccna"),
    feeNPR: 20000,
    feeNote: "Installments available",
    seats: "Limited seats (lab capacity)",
    seoTitle: "CCNA Networking Course in Nepal | DarbarTech",
    seoDescription: "Build job-ready networking skills with CCNA and MikroTik training.",
    cta: "Start Your Networking Career",
  },

  // ===== Cyber Security (2) =====
  {
    id: "c29",
    slug: "ethical-hacking-cyber-security",
    title: "Ethical Hacking & Cyber Security",
    category: "Cyber Security",
    tagline: "Defend systems the way real attackers think.",
    level: "Advanced",
    duration: "12 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Cisco",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn ethical hacking and cybersecurity defense techniques through hands-on penetration testing labs.",
    skillsGained: ["Kali Linux", "Penetration testing", "Threat detection", "Security auditing"],
    softwareTools: ["Kali Linux", "Wireshark", "Metasploit", "Burp Suite"],
    portfolioProjects: ["Penetration Test Report", "Vulnerability Assessment"],
    careerOpportunities: ["Ethical Hacker", "Cyber Security Analyst", "Security Auditor"],
    image: getCourseImage("ethical-hacking-cyber-security"),
    feeNPR: 25000,
    feeNote: "Installments available",
    seats: "Limited seats (lab capacity)",
    seoTitle: "Ethical Hacking Course in Kathmandu | DarbarTech",
    seoDescription: "Learn cybersecurity defense through hands-on penetration testing labs.",
    cta: "Start Thinking Like an Attacker",
  },
  {
    id: "c30",
    slug: "cyber-security-professional-ceh-soc-track",
    title: "Cyber Security Professional: CEH & SOC Track",
    category: "Cyber Security",
    tagline: "Get certification-ready for a career in the SOC.",
    level: "Advanced",
    duration: "14 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Cisco",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Prepare for CEH-style certification and real SOC analyst work with hands-on cloud security and OSINT labs.",
    skillsGained: ["CEH preparation", "SOC analyst workflows", "Bug bounty basics", "Cloud security", "OSINT", "Linux administration"],
    softwareTools: ["Kali Linux", "Splunk", "AWS Security Hub", "Shodan"],
    portfolioProjects: ["SOC Incident Report", "Bug Bounty Write-up", "Cloud Security Audit"],
    careerOpportunities: ["SOC Analyst", "CEH-Track Security Engineer", "Bug Bounty Hunter"],
    image: getCourseImage("cyber-security-professional-ceh-soc-track"),
    feeNPR: 30000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats (lab capacity)",
    seoTitle: "CEH & SOC Analyst Training in Nepal | DarbarTech",
    seoDescription: "Prepare for CEH-style certification and real SOC analyst work with hands-on labs.",
    cta: "Prepare for a SOC Career",
  },

  // ===== Digital Marketing (2) =====
  {
    id: "c31",
    slug: "digital-marketing-pro",
    title: "Digital Marketing Pro",
    category: "Digital Marketing",
    tagline: "Grow brands with data-driven online marketing.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google, Meta",
    internship: "Optional Internship",
    targetStudents: "Business Owners, Freelancers, Job Seekers",
    skillsGained: ["SEO & SEM", "Google & Meta Ads", "AI ad copy", "Social media analytics"],
    softwareTools: ["Google Ads", "Meta Ads Manager", "Google Analytics", "Canva"],
    portfolioProjects: ["SEO Audit", "Ad Campaign Launch", "Social Media Content Calendar"],
    careerOpportunities: ["Digital Marketer", "SEO Specialist", "Social Media Manager"],
    image: getCourseImage("digital-marketing-pro"),
    featured: true,
    feeNPR: 14000,
    feeNote: "Installments available",
    seats: "Limited seats",
    seoTitle: "Digital Marketing Course in Nepal (SEO, Google & Meta Ads) | DarbarTech",
    seoDescription: "Learn SEO, paid ads, and AI-powered content strategy in 8 weeks. Launch a real ad campaign and SEO audit — practical training for business owners and job seekers.",
    overview: "Built for people who need marketing that produces measurable results, not just theory — SEO fundamentals, running real ad campaigns on Google and Meta, and using AI tools to produce content faster without losing quality.",
    learningObjectives: ["Run an SEO audit and fix core issues", "Launch and manage Google and Meta ad campaigns", "Use AI tools for ad copy and content", "Read and act on social media analytics"],
    prerequisites: "Basic computer and internet use",
    cta: "Start Growing a Real Campaign",
    shortDescription: "Grow any brand online with SEO, paid ads and AI-powered content strategies for measurable results.",
  },
  {
    id: "c32",
    slug: "advanced-growth-marketing-automation",
    title: "Advanced Growth Marketing & Automation",
    category: "Digital Marketing",
    tagline: "Scale campaigns across every channel that matters.",
    level: "Advanced",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google, Meta",
    targetStudents: "Business Owners, Freelancers, Working Professionals",
    shortDescription: "Master advanced analytics, multi-channel ads and marketing automation to scale brands beyond the basics.",
    skillsGained: ["Google Analytics 4", "TikTok & YouTube Ads", "Email marketing", "Marketing automation"],
    softwareTools: ["Google Analytics", "TikTok Ads Manager", "Mailchimp", "HubSpot"],
    portfolioProjects: ["Multi-Channel Campaign", "Email Automation Flow", "YouTube SEO Report"],
    careerOpportunities: ["Growth Marketer", "Performance Marketing Specialist", "Marketing Automation Manager"],
    image: getCourseImage("advanced-growth-marketing-automation"),
    feeNPR: 18000,
    seoTitle: "Growth Marketing Course in Kathmandu | DarbarTech",
    seoDescription: "Master multi-channel ads, analytics, and marketing automation beyond the basics.",
    cta: "Scale Your Marketing Skills",
  },

  // ===== Career Programs (4) =====
  {
    id: "c33",
    slug: "freelancing-online-earning",
    title: "Freelancing & Online Earning",
    category: "Career Programs",
    tagline: "Start earning online with real client projects.",
    level: "Beginner",
    duration: "3 Weeks",
    learningMode: "Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Certificate",
    targetStudents: "Freelancers, Job Seekers",
    shortDescription: "Start earning online by learning to find clients, build a portfolio, and win freelance projects confidently.",
    skillsGained: ["Fiverr/Upwork setup", "Portfolio building", "Client communication", "Proposal writing"],
    softwareTools: ["Fiverr", "Upwork", "Canva", "Google Workspace"],
    portfolioProjects: ["Freelance Portfolio", "Winning Proposal Samples"],
    careerOpportunities: ["Freelancer", "Virtual Assistant", "Independent Consultant"],
    image: getCourseImage("freelancing-online-earning"),
    feeNPR: 5000,
    seoTitle: "Freelancing Course in Nepal (Fiverr & Upwork) | DarbarTech",
    seoDescription: "Learn to find clients, build a portfolio, and win freelance projects with confidence.",
    cta: "Start Earning Online",
  },
  {
    id: "c34",
    slug: "autocad-design-professional",
    title: "AutoCAD Design Professional",
    category: "Career Programs",
    tagline: "Draft the plans behind real construction projects.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Autodesk",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn professional 2D and 3D drafting in AutoCAD used across civil, architecture and engineering projects.",
    skillsGained: ["2D drafting", "3D modeling", "Technical drawing", "Project plans"],
    softwareTools: ["AutoCAD", "SketchUp"],
    portfolioProjects: ["Building Floor Plan", "3D Structure Model"],
    careerOpportunities: ["CAD Draftsman", "Civil/Architecture Assistant", "Design Engineer"],
    image: getCourseImage("autocad-design-professional"),
    feeNPR: 12000,
    seoTitle: "AutoCAD Course in Kathmandu | DarbarTech",
    seoDescription: "Learn professional 2D and 3D drafting used across civil and architecture projects.",
    cta: "Start Drafting Real Projects",
  },
  {
    id: "c35",
    slug: "kids-coding-robotics",
    title: "Kids Coding & Robotics",
    category: "Career Programs",
    tagline: "A fun first step into code, robots and AI.",
    level: "Beginner",
    duration: "8 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Weekend only",
    timing: "Weekend only",
    instituteCertificate: "Certificate",
    targetStudents: "SEE Students (ages 8-15)",
    shortDescription: "A fun, guided introduction to coding, robotics and AI for young learners building future-ready digital skills.",
    skillsGained: ["Scratch coding", "Robotics basics", "Logical thinking", "Safe AI introduction"],
    softwareTools: ["Scratch", "Arduino", "ChatGPT (guided)"],
    portfolioProjects: ["Scratch Game", "Simple Robot Build"],
    careerOpportunities: ["Foundation for Future STEM Careers"],
    image: getCourseImage("kids-coding-robotics"),
    feeNPR: 6000,
    seoTitle: "Kids Coding & Robotics Course in Nepal | DarbarTech",
    seoDescription: "A fun, guided introduction to coding, robotics, and safe AI use for ages 8–15.",
    cta: "Enroll Your Child Today",
  },
  {
    id: "c36",
    slug: "career-track-ai-automation-specialist",
    title: "Career Track: AI Automation Specialist",
    category: "Career Programs",
    tagline: "Become an in-demand AI Automation Specialist.",
    level: "Advanced",
    duration: "16 Weeks",
    learningMode: "Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Career Program",
    internship: "Internship Available",
    targetStudents: "Job Seekers, Working Professionals",
    shortDescription: "A career-focused track to become an in-demand AI Automation Specialist with a job-ready automation portfolio.",
    skillsGained: ["AI agent workflows", "No-code automation", "Business process design", "Portfolio projects"],
    softwareTools: ["LangChain", "Zapier/n8n", "OpenAI API", "Notion"],
    portfolioProjects: ["Business Automation Suite", "AI Agent Portfolio"],
    careerOpportunities: ["AI Automation Specialist", "Workflow Consultant", "Freelancer"],
    image: getCourseImage("career-track-ai-automation-specialist"),
    feeNPR: 32000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats, cohort-based intake",
    seoTitle: "AI Automation Specialist Career Track Nepal | DarbarTech",
    seoDescription: "Become an in-demand AI automation specialist with a job-ready automation portfolio.",
    cta: "Start Your AI Career Track",
  },

  // ===== Professional Diploma (1) =====
  {
    id: "c37",
    slug: "professional-computer-diploma",
    title: "Professional Computer Diploma",
    category: "Professional Diploma",
    tagline: "One complete diploma from basics to job-ready IT skills.",
    level: "Beginner to Intermediate",
    duration: "24 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Morning / Day",
    instituteCertificate: "Diploma",
    industryCertification: "Microsoft",
    internship: "Optional Internship",
    targetStudents: "SEE Students, +2 Students, Job Seekers",
    skillsGained: ["Computer fundamentals", "Typing", "Office suite", "Internet", "IT support basics"],
    softwareTools: ["MS Office", "Windows", "Internet tools"],
    portfolioProjects: ["Office Skills Portfolio", "IT Support Case Studies"],
    careerOpportunities: ["Computer Operator", "IT Support Assistant", "Office Executive"],
    image: getCourseImage("professional-computer-diploma"),
    featured: true,
    feeNPR: 18000,
    feeNote: "4-part installment plan available",
    seats: "Limited seats",
    seoTitle: "Computer Diploma Course in Kathmandu (6-Month Program) | DarbarTech",
    seoDescription: "A complete 24-week diploma covering computer fundamentals, MS Office, and IT support basics — one program from zero to job-ready.",
    overview: "For students who want one structured program that takes them from complete beginner to job-ready across computer fundamentals, Office software, and basic IT support — without having to plan a sequence of separate short courses.",
    learningObjectives: ["Operate confidently across OS, internet, and Office software", "Type accurately at a professional standard", "Handle basic IT support scenarios", "Build an IT support and office-skills portfolio"],
    prerequisites: "None",
    cta: "Start Your 6-Month Diploma",
    shortDescription: "A complete six-month diploma covering computer fundamentals, Office skills and IT support for job-ready graduates.",
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((c) => c.slug === slug);
}

export function getFeaturedCourses(count = 8): Course[] {
  return courses.filter((c) => c.featured).slice(0, count);
}

export function getRelatedCourses(course: Course, count = 3): Course[] {
  return courses
    .filter((c) => c.category === course.category && c.id !== course.id)
    .slice(0, count);
}

export function formatFee(amount: number): string {
  return `NPR ${amount.toLocaleString("en-IN")}`;
}
