// [PLACEHOLDER CONTENT - feeNPR values are estimates, replace with real Darbar Computer pricing before launch]
// [Industry Certification values are illustrative pathway names per source notes — confirm real partnerships before publishing claims]
// 37 courses across 15 categories, transcribed from darbar-computer-course-catalog-2026.md v2.0

import type { Course } from "@/types/course";

function img(cat: string, _n: number) {
  const categoryMap: Record<string, string> = {
    basic: "https://images.pexels.com/photos/10638075/pexels-photo-10638075.jpeg?auto=compress&cs=tinysrgb&w=1000",
    office: "https://images.pexels.com/photos/18471480/pexels-photo-18471480.jpeg?auto=compress&cs=tinysrgb&w=1000",
    programming: "https://images.pexels.com/photos/6424590/pexels-photo-6424590.jpeg?auto=compress&cs=tinysrgb&w=1000",
    web: "https://images.pexels.com/photos/574069/pexels-photo-574069.jpeg?auto=compress&cs=tinysrgb&w=1000",
    ai: "https://images.pexels.com/photos/6424590/pexels-photo-6424590.jpeg?auto=compress&cs=tinysrgb&w=1000",
    data: "https://images.pexels.com/photos/6424590/pexels-photo-6424590.jpeg?auto=compress&cs=tinysrgb&w=1000",
    cloud: "https://images.pexels.com/photos/6424590/pexels-photo-6424590.jpeg?auto=compress&cs=tinysrgb&w=1000",
    design: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1000",
    video: "https://images.pexels.com/photos/6424590/pexels-photo-6424590.jpeg?auto=compress&cs=tinysrgb&w=1000",
    business: "https://images.pexels.com/photos/8296990/pexels-photo-8296990.jpeg?auto=compress&cs=tinysrgb&w=1000",
    network: "https://images.pexels.com/photos/442154/pexels-photo-442154.jpeg?auto=compress&cs=tinysrgb&w=1000",
    cyber: "https://images.pexels.com/photos/6424590/pexels-photo-6424590.jpeg?auto=compress&cs=tinysrgb&w=1000",
    marketing: "https://images.pexels.com/photos/6424590/pexels-photo-6424590.jpeg?auto=compress&cs=tinysrgb&w=1000",
    career: "https://images.pexels.com/photos/17258012/pexels-photo-17258012.jpeg?auto=compress&cs=tinysrgb&w=1000",
    diploma: "https://images.pexels.com/photos/17258012/pexels-photo-17258012.jpeg?auto=compress&cs=tinysrgb&w=1000",
  };
  return categoryMap[cat] ?? categoryMap.programming;
}

export const courses: Course[] = [
  // ===== Basic Computer (3) =====
  {
    id: "c01",
    slug: "digital-literacy-essentials",
    title: "Digital Literacy Essentials",
    category: "Basic Computer",
    tagline: "Everyday computer, internet and AI skills for total beginners.",
    level: "Beginner",
    duration: "4 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Sunday",
    timing: "Morning / Day / Evening",
    instituteCertificate: "Certificate",
    targetStudents: "SEE Students, +2 Students",
    shortDescription: "Build essential computer, internet, and everyday AI skills for total beginners in just one month.",
    skillsGained: ["OS navigation", "File management", "Internet & email", "Everyday AI tools", "Digital safety"],
    softwareTools: ["Windows", "Google Workspace", "ChatGPT"],
    portfolioProjects: ["Personal Email Setup", "Basic Document Pack"],
    careerOpportunities: ["Office Assistant", "Data Entry Clerk"],
    image: img("basic", 1),
    feeNPR: 3000,
  },
  {
    id: "c02",
    slug: "speed-typing-mastery",
    title: "Speed Typing Mastery",
    category: "Basic Computer",
    tagline: "Type fast, type accurate, get exam and job ready.",
    level: "Beginner",
    duration: "4 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Sunday",
    timing: "Morning / Day / Evening",
    instituteCertificate: "Certificate",
    targetStudents: "SEE Students, +2 Students, Job Seekers",
    shortDescription: "Master fast, accurate English and Nepali typing with certified speed tests for office and exam readiness.",
    skillsGained: ["Touch-typing technique", "English & Nepali typing", "Speed & accuracy", "Keyboard shortcuts"],
    softwareTools: ["Typing Master", "RapidTyping"],
    portfolioProjects: ["Certified Speed Test Report"],
    careerOpportunities: ["Data Entry Operator", "Office Assistant"],
    image: img("basic", 2),
    feeNPR: 3000,
  },
  {
    id: "c03",
    slug: "professional-computer-operator",
    title: "Professional Computer Operator",
    category: "Basic Computer",
    tagline: "A complete beginner-to-job-ready operator package.",
    level: "Beginner",
    duration: "12 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Morning / Day",
    instituteCertificate: "Diploma",
    industryCertification: "Microsoft",
    internship: "Optional Internship",
    targetStudents: "SEE Students, +2 Students, Job Seekers",
    shortDescription: "A complete beginner-to-job-ready package combining typing, Office software, and internet skills for operator roles.",
    skillsGained: ["Typing", "MS Office", "Internet & email", "Data entry", "Basic troubleshooting", "Office etiquette"],
    softwareTools: ["MS Word", "Excel", "PowerPoint", "Google Workspace"],
    portfolioProjects: ["Office Records System", "Data Entry Portfolio"],
    careerOpportunities: ["Computer Operator", "Office Assistant", "Data Entry Officer"],
    image: img("basic", 3),
    featured: true,
    feeNPR: 9000,
    feeNote: "Installments available",
    seats: "Limited seats",
  },

  // ===== Office & Productivity (3) =====
  {
    id: "c04",
    slug: "microsoft-office-professional",
    title: "Microsoft Office Professional",
    category: "Office & Productivity",
    tagline: "Master the Office suite every workplace runs on.",
    level: "Beginner",
    duration: "8 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Sunday",
    timing: "Morning / Day / Evening",
    instituteCertificate: "Certificate",
    industryCertification: "Microsoft",
    targetStudents: "+2 Students, Job Seekers, Working Professionals",
    shortDescription: "Gain hands-on mastery of Word, Excel, PowerPoint and AI-assisted Office tools used in every workplace.",
    skillsGained: ["Word", "Excel", "PowerPoint", "Outlook", "Copilot AI basics", "Document formatting"],
    softwareTools: ["MS Word", "Excel", "PowerPoint", "Outlook", "Copilot"],
    portfolioProjects: ["Business Report", "Sales Presentation", "Budget Sheet"],
    careerOpportunities: ["Office Assistant", "Admin Executive", "Data Entry Officer"],
    image: img("office", 1),
    feeNPR: 7000,
    feeNote: "Installments available",
  },
  {
    id: "c05",
    slug: "advanced-excel-for-professionals",
    title: "Advanced Excel for Professionals",
    category: "Office & Productivity",
    tagline: "Turn spreadsheets into powerful business dashboards.",
    level: "Intermediate",
    duration: "4 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Microsoft",
    targetStudents: "Working Professionals, Business Owners",
    shortDescription: "Build powerful Excel dashboards and automate reports using pivot tables, Power Query, and advanced formulas.",
    skillsGained: ["Pivot tables", "Power Query", "Dashboards", "Advanced formulas", "Macro basics"],
    softwareTools: ["MS Excel", "Power Query", "Power BI"],
    portfolioProjects: ["Sales Dashboard", "Automated Report Template"],
    careerOpportunities: ["Data Analyst", "Finance Executive", "Business Analyst"],
    image: img("office", 2),
    feeNPR: 6500,
  },
  {
    id: "c06",
    slug: "ai-office-administration",
    title: "AI Office Administration",
    category: "Office & Productivity",
    tagline: "Run any office with AI-assisted efficiency.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Day",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Microsoft",
    internship: "Optional Internship",
    targetStudents: "Job Seekers, Working Professionals",
    shortDescription: "Learn modern office administration enhanced with AI drafting and scheduling tools to run any workplace.",
    skillsGained: ["Correspondence", "Scheduling", "AI-assisted drafting", "Record-keeping", "Workflow tools"],
    softwareTools: ["MS Office", "Outlook", "ChatGPT", "Notion"],
    portfolioProjects: ["Office Workflow System", "AI Email Templates"],
    careerOpportunities: ["Office Administrator", "Executive Assistant", "HR Coordinator"],
    image: img("office", 3),
    feeNPR: 9000,
    feeNote: "Installments available",
    seats: "Limited seats",
  },

  // ===== Programming (3) =====
  {
    id: "c07",
    slug: "software-development-foundation",
    title: "Software Development Foundation",
    category: "Programming",
    tagline: "Build the coding logic every developer starts with.",
    level: "Beginner",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Certificate",
    targetStudents: "+2 Students, Bachelor Students",
    shortDescription: "Build a strong programming foundation in C, Python and Java through logic-based, hands-on practice.",
    skillsGained: ["C/C++ basics", "Python fundamentals", "Logic building", "Problem-solving", "Java basics"],
    softwareTools: ["VS Code", "Git", "GitHub", "Python", "C++"],
    portfolioProjects: ["Console Calculator", "Student Management System"],
    careerOpportunities: ["Junior Programmer", "Trainee Developer"],
    image: img("programming", 1),
    feeNPR: 13000,
  },
  {
    id: "c08",
    slug: "dsa-competitive-programming",
    title: "DSA & Competitive Programming",
    category: "Programming",
    tagline: "Sharpen problem-solving for interviews and contests.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Certificate",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Master data structures and algorithms to crack coding interviews and competitive programming contests.",
    skillsGained: ["Data structures", "Algorithms", "Time complexity", "Interview problem patterns", "Contest practice"],
    softwareTools: ["VS Code", "Git", "LeetCode", "Codeforces"],
    portfolioProjects: ["Algorithm Visualizer", "Coding Contest Portfolio"],
    careerOpportunities: ["Software Engineer", "SDE Intern", "Backend Developer"],
    image: img("programming", 2),
    feeNPR: 14000,
    seats: "Limited seats",
  },
  {
    id: "c09",
    slug: "python-for-ai-engineering",
    title: "Python for AI Engineering",
    category: "Programming",
    tagline: "Build intelligent software using modern AI tools.",
    level: "Intermediate",
    duration: "12 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn Python programming combined with practical AI integration to build smart, automated applications.",
    skillsGained: ["Python", "OOP", "APIs", "AI libraries", "Automation scripting"],
    softwareTools: ["Python", "VS Code", "OpenAI API", "Git"],
    portfolioProjects: ["AI Chatbot", "Resume Generator", "AI Content Tool"],
    careerOpportunities: ["AI Developer", "Python Developer", "Automation Engineer"],
    image: img("programming", 3),
    feeNPR: 18000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
  },

  // ===== Web Development (5) =====
  {
    id: "c10",
    slug: "modern-frontend-engineering",
    title: "Modern Frontend Engineering",
    category: "Web Development",
    tagline: "Design beautiful, responsive websites for real businesses.",
    level: "Intermediate",
    duration: "16 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Meta",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Build modern, responsive websites and interfaces using React, Next.js, and AI-assisted coding tools.",
    skillsGained: ["HTML/CSS/JS", "React & Next.js", "Tailwind CSS", "AI pair-programming", "Responsive design"],
    softwareTools: ["VS Code", "React", "Next.js", "Tailwind CSS", "GitHub Copilot"],
    portfolioProjects: ["Restaurant Website", "Ecommerce Frontend", "School Website"],
    careerOpportunities: ["Frontend Developer", "React Developer", "UI Engineer"],
    image: img("web", 1),
    featured: true,
    feeNPR: 28000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats, cohort-based intake",
  },
  {
    id: "c11",
    slug: "backend-engineering-with-node-laravel",
    title: "Backend Engineering with Node & Laravel",
    category: "Web Development",
    tagline: "Power real applications from the server side.",
    level: "Intermediate",
    duration: "16 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn to design and build secure, scalable backend systems and APIs using Node.js and Laravel.",
    skillsGained: ["Node.js & Express", "Laravel/PHP", "REST APIs", "Databases", "Auth & JWT"],
    softwareTools: ["Node.js", "Express", "Laravel", "MySQL", "Postman"],
    portfolioProjects: ["Booking API", "Inventory System", "Auth Service"],
    careerOpportunities: ["Backend Developer", "API Engineer", "PHP/Node Developer"],
    image: img("web", 2),
    feeNPR: 28000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
  },
  {
    id: "c12",
    slug: "mern-full-stack-engineering",
    title: "MERN Full Stack Engineering",
    category: "Web Development",
    tagline: "Become a complete web developer from database to launch.",
    level: "Advanced",
    duration: "24 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Diploma",
    industryCertification: "Meta",
    internship: "Internship Available",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Become a complete web developer, building and deploying full production apps from database to launch.",
    skillsGained: ["Node.js & Express", "MongoDB/MySQL", "REST APIs", "Auth & JWT", "Deployment & CI/CD"],
    softwareTools: ["React", "Node.js", "MongoDB", "Express", "Docker", "GitHub"],
    portfolioProjects: ["Ecommerce Platform", "Job Portal", "Social Media App"],
    careerOpportunities: ["Full Stack Developer", "MERN Developer", "Software Engineer"],
    image: img("web", 3),
    featured: true,
    feeNPR: 45000,
    feeNote: "4-part installment plan available",
    seats: "Limited seats, cohort-based intake",
  },
  {
    id: "c13",
    slug: "nextjs-wordpress-development",
    title: "Next.js & WordPress Development",
    category: "Web Development",
    tagline: "Ship fast websites for startups and small businesses.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Certificate",
    targetStudents: "Bachelor Students, Freelancers, Job Seekers",
    shortDescription: "Build fast marketing sites and client websites using Next.js and WordPress, ready to deploy and sell.",
    skillsGained: ["Next.js SSR/SSG", "WordPress theming", "Elementor", "SEO basics", "Hosting & deployment"],
    softwareTools: ["Next.js", "WordPress", "Elementor", "Vercel", "cPanel"],
    portfolioProjects: ["Business Landing Page", "WordPress Business Site"],
    careerOpportunities: ["Web Developer", "WordPress Developer", "Freelancer"],
    image: img("web", 4),
    feeNPR: 14000,
  },
  {
    id: "c14",
    slug: "mobile-app-development",
    title: "Mobile App Development",
    category: "Web Development",
    tagline: "Launch real Android and iOS apps with one codebase.",
    level: "Intermediate",
    duration: "16 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers, Freelancers",
    shortDescription: "Design and launch real Android/iOS apps using Flutter and React Native with live API integration.",
    skillsGained: ["Flutter", "React Native", "Firebase", "API integration", "App deployment"],
    softwareTools: ["Flutter", "React Native", "Firebase", "Android Studio"],
    portfolioProjects: ["Food Delivery App", "Chat App", "Expense Tracker App"],
    careerOpportunities: ["Mobile App Developer", "Flutter Developer", "App Freelancer"],
    image: img("web", 5),
    feeNPR: 30000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
  },

  // ===== AI & Automation (4) =====
  {
    id: "c15",
    slug: "prompt-engineering-masterclass",
    title: "Prompt Engineering Masterclass",
    category: "AI & Automation",
    tagline: "Turn AI chat tools into a career superpower.",
    level: "Beginner",
    duration: "3 Weeks",
    learningMode: "Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Certificate",
    targetStudents: "Working Professionals, Business Owners, Freelancers",
    shortDescription: "Learn to use ChatGPT, Claude and Gemini effectively to save hours of work through smart prompting.",
    skillsGained: ["Prompt engineering", "ChatGPT/Claude/Gemini workflows", "AI content generation", "AI image & video tools"],
    softwareTools: ["ChatGPT", "Claude", "Gemini", "Cursor AI"],
    portfolioProjects: ["AI Content Playbook", "Automated Prompt Library"],
    careerOpportunities: ["AI Consultant", "Content Strategist", "Freelancer"],
    image: img("ai", 1),
    featured: true,
    feeNPR: 4500,
  },
  {
    id: "c16",
    slug: "agentic-ai-automation",
    title: "Agentic AI & Automation",
    category: "AI & Automation",
    tagline: "Build real AI agents that do the work for you.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    internship: "Optional Internship",
    targetStudents: "Job Seekers, Working Professionals",
    shortDescription: "Build real AI-powered agents and automation pipelines using modern LLM APIs and no-code tools.",
    skillsGained: ["LLM APIs", "RAG & vector databases", "Agent workflows", "No-code automation", "AI ethics basics"],
    softwareTools: ["OpenAI API", "LangChain", "Zapier/n8n", "Pinecone"],
    portfolioProjects: ["AI Support Agent", "Automated Workflow Bot"],
    careerOpportunities: ["AI Automation Engineer", "Workflow Consultant"],
    image: img("ai", 2),
    feeNPR: 16000,
    feeNote: "Installments available",
  },
  {
    id: "c17",
    slug: "llm-rag-systems-development",
    title: "LLM & RAG Systems Development",
    category: "AI & Automation",
    tagline: "Build the tech behind ChatGPT-style products.",
    level: "Advanced",
    duration: "10 Weeks",
    learningMode: "Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn to design and deploy retrieval-augmented and agentic LLM systems using modern frameworks like MCP.",
    skillsGained: ["LLM fine-tuning basics", "RAG pipelines", "Vector databases", "MCP development", "Model evaluation"],
    softwareTools: ["Python", "LangChain", "Pinecone/Chroma", "Claude API", "MCP"],
    portfolioProjects: ["RAG Knowledge Assistant", "MCP-Connected Tool", "LLM-Powered App"],
    careerOpportunities: ["LLM Developer", "AI Engineer", "Applied AI Researcher"],
    image: img("ai", 3),
    feeNPR: 22000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
  },
  {
    id: "c18",
    slug: "advanced-ai-software-engineering-diploma",
    title: "Advanced AI Software Engineering Diploma",
    category: "AI & Automation",
    tagline: "A flagship one-year diploma for AI-native developers.",
    level: "Advanced",
    duration: "48 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Advanced Diploma",
    industryCertification: "Microsoft, Google",
    internship: "Internship Available",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "A flagship one-year diploma combining full stack development with AI integration and cloud deployment skills.",
    skillsGained: ["Full stack development", "LLM integration", "Cloud deployment", "DevOps basics", "Capstone project"],
    softwareTools: ["React", "Node.js", "Python", "AWS", "Docker", "GitHub"],
    portfolioProjects: ["Capstone AI Product", "Full Stack SaaS App"],
    careerOpportunities: ["AI Software Engineer", "Full Stack Developer", "Product Engineer"],
    image: img("ai", 4),
    featured: true,
    feeNPR: 75000,
    feeNote: "6-part installment plan available",
    seats: "Limited seats, cohort-based intake",
  },

  // ===== Data Science (3) =====
  {
    id: "c19",
    slug: "machine-learning-deep-learning",
    title: "Machine Learning & Deep Learning",
    category: "Data Science",
    tagline: "Train the models powering modern AI products.",
    level: "Advanced",
    duration: "16 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn to build and evaluate machine learning and deep learning models using Python, PyTorch and TensorFlow.",
    skillsGained: ["Python, NumPy, Pandas", "ML algorithms", "Deep learning", "Model evaluation"],
    softwareTools: ["Python", "PyTorch", "TensorFlow", "Jupyter"],
    portfolioProjects: ["Price Prediction Model", "Image Classifier", "Recommendation Engine"],
    careerOpportunities: ["Machine Learning Engineer", "Data Scientist", "AI Researcher"],
    image: img("data", 1),
    feeNPR: 32000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
  },
  {
    id: "c20",
    slug: "data-analytics-with-power-bi",
    title: "Data Analytics with Power BI",
    category: "Data Science",
    tagline: "Turn raw business data into decisions.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Microsoft",
    internship: "Optional Internship",
    targetStudents: "Working Professionals, Job Seekers",
    shortDescription: "Turn raw business data into actionable dashboards and insights using SQL and Power BI.",
    skillsGained: ["SQL", "Power BI", "Data cleaning", "Data visualization", "Storytelling with data"],
    softwareTools: ["SQL", "Power BI", "Excel", "Python"],
    portfolioProjects: ["Sales Analytics Dashboard", "KPI Report"],
    careerOpportunities: ["Data Analyst", "Business Intelligence Analyst"],
    image: img("data", 2),
    feeNPR: 14000,
    seats: "Limited seats",
  },
  {
    id: "c21",
    slug: "data-engineering-with-sql-big-data",
    title: "Data Engineering with SQL & Big Data",
    category: "Data Science",
    tagline: "Build the data pipelines every AI system depends on.",
    level: "Advanced",
    duration: "12 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn to design and manage the ETL pipelines and big data infrastructure behind modern analytics and AI.",
    skillsGained: ["SQL Server", "ETL pipelines", "Apache Spark", "Big data fundamentals", "Cloud data warehousing"],
    softwareTools: ["SQL Server", "Apache Spark", "Airflow", "AWS/Azure"],
    portfolioProjects: ["ETL Pipeline", "Data Warehouse Model", "Streaming Data Dashboard"],
    careerOpportunities: ["Data Engineer", "ETL Developer", "Cloud Data Analyst"],
    image: img("data", 3),
    feeNPR: 25000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
  },

  // ===== Cloud & DevOps (1) =====
  {
    id: "c22",
    slug: "cloud-devops-engineering",
    title: "Cloud & DevOps Engineering",
    category: "Cloud & DevOps",
    tagline: "Deploy, scale and automate like a modern tech company.",
    level: "Advanced",
    duration: "12 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "AWS, Microsoft",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers, Working Professionals",
    shortDescription: "Learn to deploy, containerize and automate applications on AWS and Azure using industry DevOps practices.",
    skillsGained: ["AWS & Azure fundamentals", "Docker", "Kubernetes", "CI/CD pipelines", "Linux administration"],
    softwareTools: ["AWS", "Azure", "Docker", "Kubernetes", "Jenkins", "Linux"],
    portfolioProjects: ["Containerized App Deployment", "CI/CD Pipeline", "Cloud Infrastructure Setup"],
    careerOpportunities: ["DevOps Engineer", "Cloud Engineer", "Site Reliability Engineer"],
    image: img("cloud", 1),
    feeNPR: 28000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats",
  },

  // ===== Graphic Design (3) =====
  {
    id: "c23",
    slug: "creative-graphic-design-masterclass",
    title: "Creative Graphic Design Masterclass",
    category: "Graphic Design",
    tagline: "Turn creativity into a professional career.",
    level: "Intermediate",
    duration: "12 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Adobe",
    internship: "Optional Internship",
    targetStudents: "+2 Students, Freelancers, Job Seekers",
    shortDescription: "Master Photoshop, Illustrator and AI design tools to create logos, brochures and social media graphics.",
    skillsGained: ["Photoshop", "Illustrator", "Canva AI", "Branding design", "Print design"],
    softwareTools: ["Photoshop", "Illustrator", "Canva", "Figma"],
    portfolioProjects: ["Logo Design", "Business Card", "Brochure", "Social Media Campaign"],
    careerOpportunities: ["Graphic Designer", "Social Media Designer", "Branding Designer", "Freelancer"],
    image: img("design", 1),
    featured: true,
    feeNPR: 16000,
    feeNote: "Installments available",
    seats: "Limited seats",
  },
  {
    id: "c24",
    slug: "brand-identity-packaging-design",
    title: "Brand Identity & Packaging Design",
    category: "Graphic Design",
    tagline: "Design the visual identity brands are built on.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Day / Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Adobe",
    targetStudents: "Freelancers, Job Seekers",
    shortDescription: "Learn to build complete brand identities and packaging designs used by real product companies.",
    skillsGained: ["Brand identity systems", "Packaging design", "Print production", "Motion graphics basics", "UI animation basics"],
    softwareTools: ["Illustrator", "Photoshop", "InDesign", "After Effects"],
    portfolioProjects: ["Brand Identity Kit", "Product Packaging", "Motion Logo"],
    careerOpportunities: ["Brand Designer", "Packaging Designer", "Motion Graphics Artist"],
    image: img("design", 2),
    feeNPR: 15000,
  },
  {
    id: "c25",
    slug: "ui-ux-design-pro",
    title: "UI/UX Design Pro",
    category: "Graphic Design",
    tagline: "Design user-friendly apps and websites people love.",
    level: "Intermediate",
    duration: "12 Weeks",
    learningMode: "Physical / Online / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers, Freelancers",
    shortDescription: "Design user-friendly apps and websites using Figma, from wireframes to fully tested prototypes.",
    skillsGained: ["Figma", "Wireframing", "Prototyping", "Design systems", "Usability testing"],
    softwareTools: ["Figma", "Adobe XD", "Miro"],
    portfolioProjects: ["Mobile App Prototype", "Design System", "Usability Test Report"],
    careerOpportunities: ["UI/UX Designer", "Product Designer", "Freelancer"],
    image: img("design", 3),
    feeNPR: 18000,
    feeNote: "Installments available",
    seats: "Limited seats",
  },

  // ===== Video Production (1) =====
  {
    id: "c26",
    slug: "video-editing-motion-graphics",
    title: "Video Editing & Motion Graphics",
    category: "Video Production",
    tagline: "Edit content that stops the scroll.",
    level: "Intermediate",
    duration: "10 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Adobe",
    internship: "Optional Internship",
    targetStudents: "Freelancers, Job Seekers, Business Owners",
    shortDescription: "Edit professional videos and motion graphics for YouTube, Reels and business using industry-standard tools.",
    skillsGained: ["Premiere Pro", "After Effects", "DaVinci Resolve", "AI video tools", "Short-form editing"],
    softwareTools: ["Premiere Pro", "After Effects", "DaVinci Resolve"],
    portfolioProjects: ["YouTube Video Edit", "Reels Campaign", "Motion Graphics Intro"],
    careerOpportunities: ["Video Editor", "Motion Graphics Artist", "Content Creator"],
    image: img("video", 1),
    feeNPR: 15000,
    seats: "Limited seats",
  },

  // ===== Business & Accounting (1) =====
  {
    id: "c27",
    slug: "professional-accounting-package",
    title: "Professional Accounting Package",
    category: "Business & Accounting",
    tagline: "Manage books and GST-ready accounts with confidence.",
    level: "Beginner",
    duration: "6 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Morning / Day",
    instituteCertificate: "Certificate",
    targetStudents: "Job Seekers, Business Owners",
    shortDescription: "Learn Tally Prime and Excel to manage bookkeeping, billing and GST-ready accounts for any business.",
    skillsGained: ["Tally Prime", "GST/VAT entries", "Inventory management", "Excel for accounting"],
    softwareTools: ["Tally Prime", "Excel"],
    portfolioProjects: ["Company Books Setup", "GST Filing Practice"],
    careerOpportunities: ["Accountant", "Billing Executive", "Inventory Officer"],
    image: img("business", 1),
    feeNPR: 8000,
  },

  // ===== Networking (1) =====
  {
    id: "c28",
    slug: "network-engineering-with-ccna",
    title: "Network Engineering with CCNA",
    category: "Networking",
    tagline: "Build the networks powering Nepal's ISPs and IT firms.",
    level: "Intermediate",
    duration: "12 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Cisco",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Build job-ready networking skills with CCNA and MikroTik training used across Nepal's ISPs and IT firms.",
    skillsGained: ["Networking fundamentals", "CCNA", "MikroTik routing", "Server basics"],
    softwareTools: ["Cisco Packet Tracer", "MikroTik", "VMware"],
    portfolioProjects: ["Office Network Design", "Router Configuration Lab"],
    careerOpportunities: ["Network Engineer", "IT Support Engineer", "ISP Technician"],
    image: img("network", 1),
    feeNPR: 20000,
    feeNote: "Installments available",
    seats: "Limited seats (lab capacity)",
  },

  // ===== Cyber Security (2) =====
  {
    id: "c29",
    slug: "ethical-hacking-cyber-security",
    title: "Ethical Hacking & Cyber Security",
    category: "Cyber Security",
    tagline: "Defend systems the way real attackers think.",
    level: "Advanced",
    duration: "12 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Cisco",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn ethical hacking and cybersecurity defense techniques through hands-on penetration testing labs.",
    skillsGained: ["Kali Linux", "Penetration testing", "Threat detection", "Security auditing"],
    softwareTools: ["Kali Linux", "Wireshark", "Metasploit", "Burp Suite"],
    portfolioProjects: ["Penetration Test Report", "Vulnerability Assessment"],
    careerOpportunities: ["Ethical Hacker", "Cyber Security Analyst", "Security Auditor"],
    image: img("cyber", 1),
    feeNPR: 25000,
    feeNote: "Installments available",
    seats: "Limited seats (lab capacity)",
  },
  {
    id: "c30",
    slug: "cyber-security-professional-ceh-soc-track",
    title: "Cyber Security Professional: CEH & SOC Track",
    category: "Cyber Security",
    tagline: "Get certification-ready for a career in the SOC.",
    level: "Advanced",
    duration: "14 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Cisco",
    internship: "Optional Internship",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Prepare for CEH-style certification and real SOC analyst work with hands-on cloud security and OSINT labs.",
    skillsGained: ["CEH preparation", "SOC analyst workflows", "Bug bounty basics", "Cloud security", "OSINT", "Linux administration"],
    softwareTools: ["Kali Linux", "Splunk", "AWS Security Hub", "Shodan"],
    portfolioProjects: ["SOC Incident Report", "Bug Bounty Write-up", "Cloud Security Audit"],
    careerOpportunities: ["SOC Analyst", "CEH-Track Security Engineer", "Bug Bounty Hunter"],
    image: img("cyber", 2),
    feeNPR: 30000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats (lab capacity)",
  },

  // ===== Digital Marketing (2) =====
  {
    id: "c31",
    slug: "digital-marketing-pro",
    title: "Digital Marketing Pro",
    category: "Digital Marketing",
    tagline: "Grow brands with data-driven online marketing.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google, Meta",
    internship: "Optional Internship",
    targetStudents: "Business Owners, Freelancers, Job Seekers",
    shortDescription: "Grow any brand online with SEO, paid ads and AI-powered content strategies for measurable results.",
    skillsGained: ["SEO & SEM", "Google & Meta Ads", "AI ad copy", "Social media analytics"],
    softwareTools: ["Google Ads", "Meta Ads Manager", "Google Analytics", "Canva"],
    portfolioProjects: ["SEO Audit", "Ad Campaign Launch", "Social Media Content Calendar"],
    careerOpportunities: ["Digital Marketer", "SEO Specialist", "Social Media Manager"],
    image: img("marketing", 1),
    featured: true,
    feeNPR: 14000,
    feeNote: "Installments available",
    seats: "Limited seats",
  },
  {
    id: "c32",
    slug: "advanced-growth-marketing-automation",
    title: "Advanced Growth Marketing & Automation",
    category: "Digital Marketing",
    tagline: "Scale campaigns across every channel that matters.",
    level: "Advanced",
    duration: "8 Weeks",
    learningMode: "Physical / Online",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Google, Meta",
    targetStudents: "Business Owners, Freelancers, Working Professionals",
    shortDescription: "Master advanced analytics, multi-channel ads and marketing automation to scale brands beyond the basics.",
    skillsGained: ["Google Analytics 4", "TikTok & YouTube Ads", "Email marketing", "Marketing automation"],
    softwareTools: ["Google Analytics", "TikTok Ads Manager", "Mailchimp", "HubSpot"],
    portfolioProjects: ["Multi-Channel Campaign", "Email Automation Flow", "YouTube SEO Report"],
    careerOpportunities: ["Growth Marketer", "Performance Marketing Specialist", "Marketing Automation Manager"],
    image: img("marketing", 2),
    feeNPR: 18000,
  },

  // ===== Career Programs (4) =====
  {
    id: "c33",
    slug: "freelancing-online-earning",
    title: "Freelancing & Online Earning",
    category: "Career Programs",
    tagline: "Start earning online with real client projects.",
    level: "Beginner",
    duration: "3 Weeks",
    learningMode: "Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Certificate",
    targetStudents: "Freelancers, Job Seekers",
    shortDescription: "Start earning online by learning to find clients, build a portfolio, and win freelance projects confidently.",
    skillsGained: ["Fiverr/Upwork setup", "Portfolio building", "Client communication", "Proposal writing"],
    softwareTools: ["Fiverr", "Upwork", "Canva", "Google Workspace"],
    portfolioProjects: ["Freelance Portfolio", "Winning Proposal Samples"],
    careerOpportunities: ["Freelancer", "Virtual Assistant", "Independent Consultant"],
    image: img("career", 1),
    feeNPR: 5000,
  },
  {
    id: "c34",
    slug: "autocad-design-professional",
    title: "AutoCAD Design Professional",
    category: "Career Programs",
    tagline: "Draft the plans behind real construction projects.",
    level: "Intermediate",
    duration: "8 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Day / Evening",
    instituteCertificate: "Professional Certificate",
    industryCertification: "Autodesk",
    targetStudents: "Bachelor Students, Job Seekers",
    shortDescription: "Learn professional 2D and 3D drafting in AutoCAD used across civil, architecture and engineering projects.",
    skillsGained: ["2D drafting", "3D modeling", "Technical drawing", "Project plans"],
    softwareTools: ["AutoCAD", "SketchUp"],
    portfolioProjects: ["Building Floor Plan", "3D Structure Model"],
    careerOpportunities: ["CAD Draftsman", "Civil/Architecture Assistant", "Design Engineer"],
    image: img("career", 2),
    feeNPR: 12000,
  },
  {
    id: "c35",
    slug: "kids-coding-robotics",
    title: "Kids Coding & Robotics",
    category: "Career Programs",
    tagline: "A fun first step into code, robots and AI.",
    level: "Beginner",
    duration: "8 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Weekend only",
    timing: "Weekend only",
    instituteCertificate: "Certificate",
    targetStudents: "SEE Students (ages 8-15)",
    shortDescription: "A fun, guided introduction to coding, robotics and AI for young learners building future-ready digital skills.",
    skillsGained: ["Scratch coding", "Robotics basics", "Logical thinking", "Safe AI introduction"],
    softwareTools: ["Scratch", "Arduino", "ChatGPT (guided)"],
    portfolioProjects: ["Scratch Game", "Simple Robot Build"],
    careerOpportunities: ["Foundation for Future STEM Careers"],
    image: img("career", 3),
    feeNPR: 6000,
  },
  {
    id: "c36",
    slug: "career-track-ai-automation-specialist",
    title: "Career Track: AI Automation Specialist",
    category: "Career Programs",
    tagline: "Become an in-demand AI Automation Specialist.",
    level: "Advanced",
    duration: "16 Weeks",
    learningMode: "Online / Hybrid",
    newBatch: "Every Week",
    timing: "Evening / Weekend",
    instituteCertificate: "Career Program",
    internship: "Internship Available",
    targetStudents: "Job Seekers, Working Professionals",
    shortDescription: "A career-focused track to become an in-demand AI Automation Specialist with a job-ready automation portfolio.",
    skillsGained: ["AI agent workflows", "No-code automation", "Business process design", "Portfolio projects"],
    softwareTools: ["LangChain", "Zapier/n8n", "OpenAI API", "Notion"],
    portfolioProjects: ["Business Automation Suite", "AI Agent Portfolio"],
    careerOpportunities: ["AI Automation Specialist", "Workflow Consultant", "Freelancer"],
    image: img("career", 4),
    feeNPR: 32000,
    feeNote: "3-part installment plan available",
    seats: "Limited seats, cohort-based intake",
  },

  // ===== Professional Diploma (1) =====
  {
    id: "c37",
    slug: "professional-computer-diploma",
    title: "Professional Computer Diploma",
    category: "Professional Diploma",
    tagline: "One complete diploma from basics to job-ready IT skills.",
    level: "Beginner to Intermediate",
    duration: "24 Weeks",
    learningMode: "Physical / Hybrid",
    newBatch: "Every Week",
    timing: "Morning / Day",
    instituteCertificate: "Diploma",
    industryCertification: "Microsoft",
    internship: "Optional Internship",
    targetStudents: "SEE Students, +2 Students, Job Seekers",
    shortDescription: "A complete six-month diploma covering computer fundamentals, Office skills and IT support for job-ready graduates.",
    skillsGained: ["Computer fundamentals", "Typing", "Office suite", "Internet", "IT support basics"],
    softwareTools: ["MS Office", "Windows", "Internet tools"],
    portfolioProjects: ["Office Skills Portfolio", "IT Support Case Studies"],
    careerOpportunities: ["Computer Operator", "IT Support Assistant", "Office Executive"],
    image: img("diploma", 1),
    featured: true,
    feeNPR: 18000,
    feeNote: "4-part installment plan available",
    seats: "Limited seats",
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((c) => c.slug === slug);
}

export function getFeaturedCourses(count = 8): Course[] {
  return courses.filter((c) => c.featured).slice(0, count);
}

export function getRelatedCourses(course: Course, count = 3): Course[] {
  return courses
    .filter((c) => c.category === course.category && c.id !== course.id)
    .slice(0, count);
}

export function formatFee(amount: number): string {
  return `NPR ${amount.toLocaleString("en-IN")}`;
}
